# Generated by Django 4.2.2 on 2024-10-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
