# Generated by Django 4.2.2 on 2024-11-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocos',
            new_name='Bloco',
        ),
    ]
