# Generated by Django 4.2.2 on 2024-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_blocos_bloco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={'ordering': ['id'], 'verbose_name': '2 - Conteúdo', 'verbose_name_plural': '2 - Conteúdos'},
        ),
        migrations.AlterModelOptions(
            name='tipobloco',
            options={'ordering': ['id'], 'verbose_name': '1 - Tipo de Bloco', 'verbose_name_plural': '1 - Tipos de Blocos'},
        ),
        migrations.AddField(
            model_name='conteudo',
            name='descricao_3',
            field=models.CharField(blank=True, help_text='Descrição mais curta até 200 caracteres', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='descricao_4',
            field=models.CharField(blank=True, help_text='Descrição mais curta até 200 caracteres', max_length=200, null=True),
        ),
    ]
